
### added 'row.names=1' to each time we read in file
me <- read.table("Raw_Data/AncestryDNA_LI.txt", sep="\t", header=TRUE,row.names=1)
mom <- read.table("Raw_Data/AncestryDNA_BM.txt", sep="\t", header=TRUE,row.names=1)
dad <- read.table("Raw_Data/AncestryDNA_DI.txt", sep="\t", header=TRUE,row.names=1)

pgf <- read.table("Raw_Data/AncestryDNA_FI.txt", sep="\t", header=TRUE,row.names=1)
mgm <- read.table("Raw_Data/AncestryDNA_MH.txt", sep="\t", header=TRUE,row.names=1)
mgf <- read.table("Raw_Data/AncestryDNA_RM.txt", sep="\t", header=TRUE,row.names=1)

source('code/R-Functions-DAD-1GP.r')

plot_chromosome_one_grandparent(chrom = 1, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 2, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 3, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 4, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 5, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 6, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 7, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 8, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 9, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 10, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 11, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 12, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 13, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 14, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 15, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 16, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 17, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 18, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 19, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 20, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 21, output_dir = 'Paternal_Plots/')
plot_chromosome_one_grandparent(chrom = 22, output_dir = 'Paternal_Plots/')